import { Router } from 'express';
import { verifyToken } from '../middleware/verifyToken';
import { checkIsActive } from '../middleware/checkIsActive';
import authRouter from './auth/auth.route';
import companiesRouter from './companies/companies.route';
import tenantsRouter from './tenants/tenants.route';
import materialSuppliersRouter from './material-suppliers/material-suppliers.route';
import categoriesRouter from './categories/categories.route';
import usersRouter from './users/users.route';
import statsRouter from './stats/stats.route';
import filesRouter from './files/files.route';
import projectsRouter from './projects/projects.route';
import tendersRouter from './tenders/tenders.route';
import tenderInvitationsRouter from './tender-invitations/tender-invitations.route';
import tenderOfferFilesRouter from './tender-offer-files/tender-offer-files.route';
import tenderComparisonsRouter from './tender-comparisons/tender-comparisons.route';
import tenderItemsRouter from './tender-items/tender-items.route';
import tenderItemNotesRouter from './tender-item-notes/tender-item-notes.route';
import tenderAwardsRouter from './tender-awards/tender-awards.route';
import tenderAuditLogsRouter from './tender-audit-logs/tender-audit-logs.route';
import threeDModelsRouter from './3d-models/3d-models.route';
import paymentsRouter from './payments/payments.route';
import propertyOwnersRouter from './property-owners/property-owners.route';
import paymentPlansRouter from './payment-plans/payment-plans.route';

const baseRouter = Router();

baseRouter.use('/auth', authRouter);
baseRouter.use('/companies', verifyToken, checkIsActive, companiesRouter);
baseRouter.use('/companies/:companyId/files', verifyToken, checkIsActive, filesRouter);
baseRouter.use('/tenants', verifyToken, checkIsActive, tenantsRouter);
baseRouter.use('/material-suppliers', verifyToken, checkIsActive, materialSuppliersRouter);
baseRouter.use('/categories', verifyToken, checkIsActive, categoriesRouter);
baseRouter.use('/admin/users', verifyToken, checkIsActive, usersRouter);
baseRouter.use('/admin/stats', verifyToken, checkIsActive, statsRouter);
baseRouter.use('/projects', verifyToken, checkIsActive, projectsRouter);
baseRouter.use('/tenders', verifyToken, checkIsActive, tendersRouter);
baseRouter.use('/tenders/:tenderId/items', verifyToken, checkIsActive, tenderItemsRouter);
baseRouter.use('/tenders/:tenderId/invitations', verifyToken, checkIsActive, tenderInvitationsRouter);
baseRouter.use('/tenders/:tenderId/offer-files', verifyToken, checkIsActive, tenderOfferFilesRouter);
baseRouter.use('/tenders/:tenderId/comparison', verifyToken, checkIsActive, tenderComparisonsRouter);
baseRouter.use('/tenders/:tenderId/item-notes', verifyToken, checkIsActive, tenderItemNotesRouter);
baseRouter.use('/tenders/:tenderId/awards', verifyToken, checkIsActive, tenderAwardsRouter);
baseRouter.use('/tenders/:tenderId/audit-log', verifyToken, checkIsActive, tenderAuditLogsRouter);
baseRouter.use('/', verifyToken, checkIsActive, paymentsRouter);
baseRouter.use('/', verifyToken, checkIsActive, propertyOwnersRouter);
baseRouter.use('/', verifyToken, checkIsActive, paymentPlansRouter);
baseRouter.use('/', verifyToken, checkIsActive, threeDModelsRouter);

export default baseRouter;
